@HtmlPdfBox_HostAddress = http://localhost:8080

POST {{HtmlPdfBox_HostAddress}}/render/html
Content-Type: application/json
X-Api-Key: PleaseConfigureThis

{
  "Html": "<html><body><strong>hello world</strong></body></html>"
}
###

POST {{HtmlPdfBox_HostAddress}}/render/url
Content-Type: application/json
X-Api-Key: PleaseConfigureThis

{
  "Url": "https://www.google.com"
}
###